apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  namespace: 7372268-test
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: gp3-csi   # ← uncomment/set if your cluster's default
  #                               StorageClass isn't what you want
  resources:
    requests:
      storage: 10Gi   # ← size to taste
