apiVersion: v1
kind: Secret
metadata:
  name: mgo-backend-secret
  namespace: 7372268-test          # ← your namespace
type: Opaque
stringData:
  NEO4J_PASSWORD: "Asdf123$"            # ← Neo4j password
  JWT_SECRET: "tO7E8uCjD5rXpQl0FhKwV2yMz4bJnAi9sGeR3kTzXvNmPuLsDq8W"                # ← any long random string
  LDAP_URL: "ldaps://ldap-arl.gcc.nam.gm.com:636"  # ← your Domain Controller
  LDAP_DOMAIN: "gcc.nam.gm.com"              # ← your AD domain
  LDAP_BIND_DN: "CN=SI_MFG_7372268_ARL,OU=Service Accounts,OU=People,OU=EDS,OU=Service Provider,OU=Domain,DC=GCC,DC=mfg,DC=ad,DC=gm,DC=com"  # ← service account
  LDAP_BIND_PASSWORD: "Hfi7V3_J]u*U7x@[hr_@yHGC?zAzzs2#"       # ← service account password
